name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 1.0.3
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  android_alarm_manager_plus: ^2.1.0
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.2.2
  flutter_local_notifications: ^13.0.0
  just_audio: ^0.9.30
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.0.16
  timezone: ^0.9.0
  vibration: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: AlarmPlugin